### ISSUE TITLE
About “Add Template” UI 

### ISSUE THREAD

**Issue by b-marisa** [Javran/poi-plugin-avatar-adjuster#1]
The number  is useless after the shipclass. Recommended deleting.

匹配舰种
海防艦 (1)   <- this (1)

**Comment by Javran** [comment]
I think you meant to open an issue for poi-plugin-leveling.

It's there for a reason, how would you otherwise distinguish `戦艦 (8)` from `戦艦 (9)` without number?

**Comment by Javran** [comment]
I'm closing this issue, I have a plan to overhaul and redesign some parts of leveling anyways and "Add Template" ui is one part of it.

For further questions I recommend openning an issue to https://github.com/poooi/poi-plugin-leveling/issues and we can talk over there, things can be tracked more easily that way.
